nelmio_api_doc:
    documentation:
        info:
            title: eSGBU API
            description: REST API to handle eSGBU database.
            version: 1.5.4
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!doc$) # Accepts routes under /api except /api/doc
