monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size:  50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!action"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        action:
            type: rotating_file
            max_files: 365
            level: notice
            path: "%kernel.logs_dir%/%kernel.environment%.action.log"
            channels: ["action"]
        doctrine:
            type: rotating_file
            max_files: 2
            level: debug
            path: "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
            channels: ["doctrine"]

#        swift:
#            type: swift_mailer
#            from_email: prat@cines.fr
#            to_email: prat@cines.fr
#            channels: [ '!event' ]
#            subject: "ESGBU: Oups?! (Monolog mail sink)"
#            level: debug
#            #formatter: AppBundle\Service\CinesMultilineLogFormatter
#            formatter: monolog.formatter.html
#            content_type: text/html
